"""BayesIQ Dashboard — Generated by BayesIQ Data Audit Kit."""

import json
import os
import re

import pandas as pd
import plotly.express as px
import streamlit as st

st.set_page_config(page_title="BayesIQ Dashboard", layout="wide")


def _fmt_period(series):
    """Shorten period strings for compact x-axis labels."""
    def _shorten(s):
        # Weekly: "2025-12-01/2025-12-07" → "Dec 1"
        if "/" in s:
            s = s.split("/")[0]
        # Monthly: "2025-12" → "Dec '25"
        parts = s.split("-")
        if len(parts) >= 2:
            import calendar
            try:
                mon = calendar.month_abbr[int(parts[1])]
                if len(parts) == 2:
                    return f"{mon} '{parts[0][2:]}"
                return f"{mon} {int(parts[2])}"
            except (ValueError, IndexError):
                pass
        return s
    return series.map(_shorten)


def _humanize_label(col_name):
    """Convert snake_case column name to human-readable axis label."""
    return col_name.replace("_", " ").title()


def _polish_fig(fig, y_col, show_legend=True):
    """Apply consistent axis and legend polish to a Plotly figure."""
    fig.update_yaxes(title_text=_humanize_label(y_col))
    fig.update_xaxes(title_text="", tickangle=-30)
    if not show_legend:
        fig.update_layout(showlegend=False)

@st.cache_data
def load_data(path):
    """Load and clean the dataset from a file path."""
    if path.endswith('.parquet'):
        df = pd.read_parquet(path)
    else:
        df = pd.read_csv(path)

    if "admission_date" in df.columns:
        df["admission_date"] = pd.to_datetime(df["admission_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["patient_id", "admission_date", "discharge_date", "department", "provider_type", "insurance_type", "facility", "diagnosis_code", "drg_code", "charge_amount", "length_of_stay", "readmission_flag", "discharge_flag", "valid_coding_flag", "encounter_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


@st.cache_data
def load_uploaded(file):
    """Load and clean a dataset from an uploaded file."""
    if file.name.endswith('.parquet'):
        df = pd.read_parquet(file)
    else:
        df = pd.read_csv(file)

    if "admission_date" in df.columns:
        df["admission_date"] = pd.to_datetime(df["admission_date"], utc=True)

    # Remove near-duplicate rows
    dedup_cols = ["patient_id", "admission_date", "discharge_date", "department", "provider_type", "insurance_type", "facility", "diagnosis_code", "drg_code", "charge_amount", "length_of_stay", "readmission_flag", "discharge_flag", "valid_coding_flag", "encounter_flag"]
    before = len(df)
    df = df.drop_duplicates(subset=dedup_cols, keep='first')
    after = len(df)
    df.attrs["rows_deduped"] = before - after

    return df


def main():
    st.title("BayesIQ Data Dashboard")

    st.sidebar.header("Data Source")
    uploaded_file = st.sidebar.file_uploader(
        "Upload CSV or Parquet",
        type=["csv", "parquet", "pq"],
        help="Drag and drop a file here, or click to browse."
    )
    default_path = "data/raw_month_3.csv"
    data_path = st.sidebar.text_input("Or enter file path", value=default_path)

    # Load from upload or path
    df = None
    if uploaded_file is not None:
        try:
            df = load_uploaded(uploaded_file)
        except Exception as e:
            st.error(f"Could not load uploaded file: {e}")
            return
    elif data_path:
        try:
            df = load_data(data_path)
        except Exception as e:
            st.error(f"Could not load dataset: {e}")
            return
    else:
        st.info("Upload a file or enter a dataset path in the sidebar to get started.")
        return

    # Auto-detect period: weekly for short datasets, monthly otherwise
    _period = "M"
    if "admission_date" in df.columns:
        _ts_range = df["admission_date"].max() - df["admission_date"].min()
        if _ts_range.days <= 45:
            _period = "W"

    # --- Column Role Wizard ---
    roles_file = os.path.join(os.path.dirname(__file__), "column_roles_resolved.json")
    saved_roles = {}
    if os.path.exists(roles_file):
        with open(roles_file) as _f:
            saved_roles = json.load(_f)

    ambiguous_cols = ["diagnosis_code", "drg_code"]
    unresolved = [c for c in ambiguous_cols if c not in saved_roles]

    if unresolved:
        st.info("Some columns contain embedded numbers (e.g. \"5 Pack\", \"8 MILLIGRAM\"). Tell us how to use them.")
        with st.expander("Configure column roles", expanded=True):
            wizard_roles = {}
            st.markdown("**diagnosis_code** — e.g. A01.0, B02.1, C03.2")
            diagnosis_code_role = st.radio(
                "Role for diagnosis_code",
                ['Use as filter (categorical)', 'Use as ordered axis (sort by number)', 'Use as numeric multiplier', 'Ignore this column'],
                index=0,
                key="wizard_diagnosis_code",
                horizontal=True,
            )
            wizard_roles["diagnosis_code"] = {"role": diagnosis_code_role}
            if "multiplier" in diagnosis_code_role.lower():
                diagnosis_code_target = st.selectbox(
                    "Multiply against",
                    ["charge_amount", "length_of_stay", "readmission_flag", "discharge_flag", "valid_coding_flag", "encounter_flag"],
                    index=0,
                    key="wizard_diagnosis_code_target",
                )
                wizard_roles["diagnosis_code"]["multiply_against"] = diagnosis_code_target

            st.markdown("**drg_code** — e.g. DRG-001, DRG-002, DRG-003")
            drg_code_role = st.radio(
                "Role for drg_code",
                ['Use as filter (categorical)', 'Use as ordered axis (sort by number)', 'Use as numeric multiplier', 'Ignore this column'],
                index=0,
                key="wizard_drg_code",
                horizontal=True,
            )
            wizard_roles["drg_code"] = {"role": drg_code_role}
            if "multiplier" in drg_code_role.lower():
                drg_code_target = st.selectbox(
                    "Multiply against",
                    ["charge_amount", "length_of_stay", "readmission_flag", "discharge_flag", "valid_coding_flag", "encounter_flag"],
                    index=0,
                    key="wizard_drg_code_target",
                )
                wizard_roles["drg_code"]["multiply_against"] = drg_code_target

            if st.button("Save column roles", type="primary"):
                saved_roles.update(wizard_roles)
                with open(roles_file, 'w') as _f:
                    json.dump(saved_roles, _f, indent=2)
                st.success("Column roles saved. Reloading...")
                st.rerun()

    # Apply resolved column roles
    for col_name, role_info in saved_roles.items():
        if col_name not in df.columns:
            continue
        role_str = role_info.get("role", "")
        if "multiplier" in role_str.lower():
            target = role_info.get("multiply_against")
            if target and target in df.columns:
                nums = df[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
                derived_name = role_info.get("derived_metric_name", f"{target}_x_{col_name}")
                df[derived_name] = df[target] * nums
        elif "ordered" in role_str.lower() or "ordinal" in role_str.lower():
            sort_order = df[col_name].drop_duplicates().to_frame()
            sort_order["_sort"] = sort_order[col_name].astype(str).str.extract(r"(\d+(?:\.\d+)?)", expand=False).astype(float)
            sort_order = sort_order.sort_values("_sort")[col_name].tolist()
            df[col_name] = pd.Categorical(df[col_name], categories=sort_order, ordered=True)

    # --- Sidebar Filters ---
    st.sidebar.header("Filters")

    if "admission_date" in df.columns:
        min_date = df["admission_date"].min().date()
        max_date = df["admission_date"].max().date()
        date_range = st.sidebar.date_input(
            "Date Range",
            value=(min_date, max_date),
            min_value=min_date,
            max_value=max_date,
        )
        if len(date_range) == 2:
            df = df[(df["admission_date"].dt.date >= date_range[0]) &
                    (df["admission_date"].dt.date <= date_range[1])]

    if "department" in df.columns:
        department_opts = sorted(df["department"].dropna().unique().tolist())
        department_sel = st.sidebar.multiselect(
            "department",
            options=department_opts,
            default=department_opts,
        )
        df = df[df["department"].isin(department_sel)]

    if "provider_type" in df.columns:
        provider_type_opts = sorted(df["provider_type"].dropna().unique().tolist())
        provider_type_sel = st.sidebar.multiselect(
            "provider_type",
            options=provider_type_opts,
            default=provider_type_opts,
        )
        df = df[df["provider_type"].isin(provider_type_sel)]

    if "insurance_type" in df.columns:
        insurance_type_opts = sorted(df["insurance_type"].dropna().unique().tolist())
        insurance_type_sel = st.sidebar.multiselect(
            "insurance_type",
            options=insurance_type_opts,
            default=insurance_type_opts,
        )
        df = df[df["insurance_type"].isin(insurance_type_sel)]

    if "facility" in df.columns:
        facility_opts = sorted(df["facility"].dropna().unique().tolist())
        facility_sel = st.sidebar.multiselect(
            "facility",
            options=facility_opts,
            default=facility_opts,
        )
        df = df[df["facility"].isin(facility_sel)]

    if "diagnosis_code" in df.columns:
        diagnosis_code_opts = sorted(df["diagnosis_code"].dropna().unique().tolist())
        diagnosis_code_sel = st.sidebar.multiselect(
            "diagnosis_code",
            options=diagnosis_code_opts,
            default=diagnosis_code_opts,
        )
        df = df[df["diagnosis_code"].isin(diagnosis_code_sel)]

    if "drg_code" in df.columns:
        drg_code_opts = sorted(df["drg_code"].dropna().unique().tolist())
        drg_code_sel = st.sidebar.multiselect(
            "drg_code",
            options=drg_code_opts,
            default=drg_code_opts,
        )
        df = df[df["drg_code"].isin(drg_code_sel)]

    if "length_of_stay" in df.columns:
        length_of_stay_opts = sorted(df["length_of_stay"].dropna().unique().tolist())
        length_of_stay_sel = st.sidebar.multiselect(
            "length_of_stay",
            options=length_of_stay_opts,
            default=length_of_stay_opts,
        )
        df = df[df["length_of_stay"].isin(length_of_stay_sel)]

    if "readmission_flag" in df.columns:
        readmission_flag_opts = sorted(df["readmission_flag"].dropna().unique().tolist())
        readmission_flag_sel = st.sidebar.multiselect(
            "readmission_flag",
            options=readmission_flag_opts,
            default=readmission_flag_opts,
        )
        df = df[df["readmission_flag"].isin(readmission_flag_sel)]

    if "valid_coding_flag" in df.columns:
        valid_coding_flag_opts = sorted(df["valid_coding_flag"].dropna().unique().tolist())
        valid_coding_flag_sel = st.sidebar.multiselect(
            "valid_coding_flag",
            options=valid_coding_flag_opts,
            default=valid_coding_flag_opts,
        )
        df = df[df["valid_coding_flag"].isin(valid_coding_flag_sel)]

    st.sidebar.metric("Rows (filtered)", f"{len(df):,}")
    deduped = df.attrs.get("rows_deduped", 0)
    if deduped:
        st.sidebar.metric("Rows deduped", f"{deduped:,}")

    tabs = st.tabs(["Metrics", "Data Quality", "Raw Data"])

    with tabs[0]:
        st.header("Business Metrics")

        _compact = dict(height=260, margin=dict(l=40, r=20, t=40, b=30),
                        title_font_size=13,
                        legend=dict(orientation="h", y=-0.25, font=dict(size=10)))

        _dim_options = ["Topline", "department", "provider_type", "insurance_type", "facility"]
        _sel_dim = st.radio("Dimension", _dim_options, index=0, horizontal=True, key="dim_radio")
        _dim_col = None if _sel_dim == "Topline" else _sel_dim

        # When in dimension mode, only show legend on first chart
        _legend_shown = False

        # --- Row 1 ---
        r1c1, r1c2, r1c3 = st.columns(3)

        with r1c1:
            num_df = df[(df["readmission_flag"] == 1)]
            den_df = df[(df["discharge_flag"] == 1)]
            if _dim_col and _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["admission_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["admission_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "readmission_rate"]
                ratio_dim["period"] = _fmt_period(ratio_dim["period"].astype(str))
                if ratio_dim.empty:
                    st.info("No data for Readmission Rate.")
                else:
                    fig = px.line(ratio_dim, x="period", y="readmission_rate", color=_dim_col, title="Readmission Rate (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "readmission_rate", show_legend=not _legend_shown)
                    _legend_shown = True
                    st.plotly_chart(fig, use_container_width=True)
            else:
                den_grouped = den_df.groupby(den_df["admission_date"].dt.to_period(_period)).size()
                num_grouped = num_df.groupby(num_df["admission_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
                ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
                ratio_df.columns = ["period", "readmission_rate"]
                ratio_df["period"] = _fmt_period(ratio_df["period"].astype(str))
                if ratio_df.empty:
                    st.info("No data for Readmission Rate.")
                else:
                    fig = px.line(ratio_df, x="period", y="readmission_rate", title="Readmission Rate (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "readmission_rate")
                    st.plotly_chart(fig, use_container_width=True)

        with r1c2:
            metric_df = df
            if _dim_col and _dim_col in metric_df.columns:
                grouped = metric_df.groupby([metric_df["admission_date"].dt.to_period(_period), _dim_col]).size().reset_index()
                grouped.columns = ["period", _dim_col, "throughput"]
                grouped["period"] = _fmt_period(grouped["period"].astype(str))
                fig = px.bar(grouped, x="period", y="throughput", color=_dim_col, title="Throughput", barmode="group")
            else:
                grouped = metric_df.groupby(metric_df["admission_date"].dt.to_period(_period)).size().reset_index()
                grouped.columns = ["period", "throughput"]
                grouped["period"] = _fmt_period(grouped["period"].astype(str))
                fig = px.bar(grouped, x="period", y="throughput", title="Throughput")
            fig.update_layout(**_compact)
            _polish_fig(fig, "throughput", show_legend=not _legend_shown and _dim_col is not None)
            if _dim_col:
                _legend_shown = True
            st.plotly_chart(fig, use_container_width=True)

        with r1c3:
            metric_df = df
            if "charge_amount" not in metric_df.columns:
                st.warning("Column \"charge_amount\" not found — skipping Charge Capture.")
            else:
                if _dim_col and _dim_col in metric_df.columns:
                    grouped = metric_df.groupby([metric_df["admission_date"].dt.to_period(_period), _dim_col])["charge_amount"].sum().reset_index()
                    grouped.columns = ["period", _dim_col, "charge_capture"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="charge_capture", color=_dim_col, title="Charge Capture ($)", barmode="group")
                else:
                    grouped = metric_df.groupby(metric_df["admission_date"].dt.to_period(_period))["charge_amount"].sum().reset_index()
                    grouped.columns = ["period", "charge_capture"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.bar(grouped, x="period", y="charge_capture", title="Charge Capture ($)")
                fig.update_layout(**_compact)
                _polish_fig(fig, "charge_capture", show_legend=not _legend_shown and _dim_col is not None)
                if _dim_col:
                    _legend_shown = True
                st.plotly_chart(fig, use_container_width=True)

        # --- Row 2 ---
        r2c1, r2c2, r2c3 = st.columns(3)

        with r2c1:
            metric_df = df
            if "length_of_stay" not in metric_df.columns:
                st.warning("Column \"length_of_stay\" not found — skipping Length Of Stay.")
            else:
                if _dim_col and _dim_col in metric_df.columns:
                    grouped = metric_df.groupby([metric_df["admission_date"].dt.to_period(_period), _dim_col])["length_of_stay"].mean().reset_index()
                    grouped.columns = ["period", _dim_col, "length_of_stay"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.line(grouped, x="period", y="length_of_stay", color=_dim_col, title="Length Of Stay (days)", markers=True)
                else:
                    grouped = metric_df.groupby(metric_df["admission_date"].dt.to_period(_period))["length_of_stay"].mean().reset_index()
                    grouped.columns = ["period", "length_of_stay"]
                    grouped["period"] = _fmt_period(grouped["period"].astype(str))
                    fig = px.line(grouped, x="period", y="length_of_stay", title="Length Of Stay (days)", markers=True)
                fig.update_layout(**_compact)
                _polish_fig(fig, "length_of_stay", show_legend=not _legend_shown and _dim_col is not None)
                if _dim_col:
                    _legend_shown = True
                st.plotly_chart(fig, use_container_width=True)

        with r2c2:
            num_df = df[(df["valid_coding_flag"] == 1)]
            den_df = df[(df["encounter_flag"] == 1)]
            if _dim_col and _dim_col in num_df.columns:
                num_dim = num_df.groupby([num_df["admission_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                den_dim = den_df.groupby([den_df["admission_date"].dt.to_period(_period), _dim_col]).size().unstack(fill_value=0)
                ratio_dim = (num_dim / den_dim).stack().reset_index()
                ratio_dim.columns = ["period", _dim_col, "coding_accuracy"]
                ratio_dim["period"] = _fmt_period(ratio_dim["period"].astype(str))
                if ratio_dim.empty:
                    st.info("No data for Coding Accuracy.")
                else:
                    fig = px.line(ratio_dim, x="period", y="coding_accuracy", color=_dim_col, title="Coding Accuracy (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "coding_accuracy", show_legend=not _legend_shown and _dim_col is not None)
                    if _dim_col:
                        _legend_shown = True
                    st.plotly_chart(fig, use_container_width=True)
            else:
                den_grouped = den_df.groupby(den_df["admission_date"].dt.to_period(_period)).size()
                num_grouped = num_df.groupby(num_df["admission_date"].dt.to_period(_period)).size().reindex(den_grouped.index, fill_value=0)
                ratio_df = (num_grouped / den_grouped).fillna(0).reset_index()
                ratio_df.columns = ["period", "coding_accuracy"]
                ratio_df["period"] = _fmt_period(ratio_df["period"].astype(str))
                if ratio_df.empty:
                    st.info("No data for Coding Accuracy.")
                else:
                    fig = px.line(ratio_df, x="period", y="coding_accuracy", title="Coding Accuracy (%)", markers=True)
                    fig.update_layout(**_compact)
                    _polish_fig(fig, "coding_accuracy")
                    st.plotly_chart(fig, use_container_width=True)

        with r2c3:
            st.markdown("##### KPI Summary")
            st.markdown(f"**Total Rows:** {len(df):,}")
            if "admission_date" in df.columns:
                _min = df["admission_date"].min().strftime("%Y-%m-%d")
                _max = df["admission_date"].max().strftime("%Y-%m-%d")
                st.markdown(f"**Date Range:** {_min} to {_max}")
            if "length_of_stay" in df.columns:
                _avg_los = df["length_of_stay"].mean()
                st.markdown(f"**Avg Length of Stay:** {_avg_los:.1f} days")

    with tabs[1]:
        st.header("Data Quality Summary")
        st.metric("Total Issues Found", 3)

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Critical", 0)
        col2.metric("High", 2)
        col3.metric("Medium", 1)
        col4.metric("Low", 0)

        st.info("This dashboard applies automatic cleaning: value canonicalization and near-duplicate deduplication. The issues below were detected in the raw data before cleaning.")

        st.subheader("Findings")
        st.markdown("**1. [HIGH]** Near-duplicate rows detected (50 rows)")
        st.markdown("**2. [HIGH]** Null values in required column: patient_id (25 rows)")
        st.markdown("**3. [MEDIUM]** readmission_rate misreported for 2025-12 (off by +5.7%) (1 rows)")

    with tabs[2]:
        st.header("Raw Data")
        st.dataframe(df.head(1000), use_container_width=True)


if __name__ == "__main__":
    main()
